### ISSUE TITLE
BSP/Src/audio_record.c STM32F407VG Keilc V5

### ISSUE THREAD

**Issue by luan12689** [STMicroelectronics/stm32-bsp-common#1]
Hello sir. I'm a student working on audio_record.c in BSP example. May i ask what i have to change to increase the time of recording in this project. When i run this example the time of recording very small (about 1s). Looking forward to hearing from you.
Thank you very much

**Comment by ALABSTM** [comment]
Hi @luan12689,

Excuse this late reply. Generally, for support requests like yours, you can get support from the **ST Community** by posting your request in the adequate topic from [this](https://community.st.com/s/topiccatalog) list.

With regards,
